Alve Operating System/Alve OS.sln, Alve Operating System/Alve OS/Kernel.cs, Alve Operating System/Alve OS/System/Strings.cs, Alve Operating System/Alve OS/System/Variables.cs
Stocker toutes les variables au même endroit, on peut donc y accéder plus facilement de n'importe quel classe.
```namespace Alve_OS.System
{
class Variables
{
public static bool running;
public static string version = "0.1";
}
}
```
```
Console.WriteLine("Welcome to Alve Operating System v" + Variables.version + " !");
```
Classe Strings.cs
```
class Strings
{
public static void Display(string lang, string ToTranslate)
{
switch (lang)
{
case "fr_FR":
switch (ToTranslate)
{
case "shutdown":
Console.WriteLine("Extinction en cours...");
break;
}
break;
case "en_US":
switch (ToTranslate)
{
case "shutdown":
Console.WriteLine("Shutting Down...");
break;
}
break;
}
}
}
```
```
Strings.Display("fr_FR", "shutdown");
```
=> Variables + Lang

Alve Operating System/Alve OS/System/Translation/ASCII.cs, Alve Operating System/Alve OS/System/Translation/Help.cs, Alve Operating System/Alve OS/System/Translation/Text.cs
ASCII.é
ASCII.è
ASCII.à
ASCII.ê
=> ASCII Support

Alve Operating System/Alve OS/Alve_OS.csproj, Alve Operating System/Alve OS/Alve_OSBoot.Cosmos, Alve Operating System/Alve OS/Apps/User/Editor.cs, Alve Operating System/Alve OS/Shell/Interpreter.cs, Alve Operating System/Alve OS/System/Translation/Text/Help.cs, Alve Operating System/Alve OS/System/Translation/Text/Text.cs
mkfil now run the editor to create a new file.
prfil shows file in the editor and we can edit it.
=> Text Editor.

Alve Operating System/Alve OS/Alve_OSBoot.Cosmos, Alve Operating System/Alve OS/Kernel.cs, Alve Operating System/Alve OS/Shell/Interpreter.cs, Alve Operating System/Alve OS/System/Login.cs, Alve Operating System/Alve OS/System/Security/MD5.cs, Alve Operating System/Alve OS/System/Setup.cs, Alve Operating System/Alve OS/System/SetupInit.cs, Alve Operating System/Alve OS/System/Translation/Text/Help.cs, Alve Operating System/Alve OS/System/Translation/Text/Text.cs, Alve Operating System/Alve OS/System/Users/UserLevel.cs, Alve Operating System/Alve OS/System/Users/Users.cs, Alve Operating System/Alve OS/System/WelcomeMessage.cs, README.md
* MD5 Security
* Multi Users
* Setup Assistant step by step
* File type in explorer with "dir" command
* Creation of user with "settings adduser"
Le code est a revisité plus tard. Tout fonctionne.
=> Users, Setup, Explorer and MD5

Alve Operating System/Alve OS.sln, Alve Operating System/Alve OS/Alve_OSBoot.Cosmos, Alve Operating System/Alve OS/Kernel.cs, Alve Operating System/Alve OS/Shell/Interpreter.cs, Alve Operating System/Alve OS/System/Translation/Text/Text.cs, Alve Operating System/Alve_OS_Core/Alve_OS_Core.csproj, Alve Operating System/Alve_OS_Core/Alve_OS_CoreBoot.Cosmos, Alve Operating System/Alve_OS_HAL/Alve_OS_HAL.csproj, Alve Operating System/Alve_OS_HAL/Alve_OS_HALBoot.Cosmos, Alve Operating System/Alve_OS_HAL/CPU.cs, Alve Operating System/Alve_OS_System/Alve_OS_System.csproj, Alve Operating System/Alve_OS_System/Alve_OS_SystemBoot.Cosmos, Alve Operating System/Alve_OS_System/Power.cs
I implemented Cosmos Rings to Alve with a "get RAM" test.
=> Alve with Cosmos rings.

Alve Operating System/Alve OS/Kernel.cs, Alve Operating System/Alve OS/Shell/Interpreter.cs, Alve Operating System/Alve OS/System/Computer/Color.cs, Alve Operating System/Alve OS/System/Crash.cs, Alve Operating System/Alve OS/System/Drawable/Logo.cs, Alve Operating System/Alve OS/System/Drawable/WelcomeMessage.cs, Alve Operating System/Alve OS/System/Security/MD5.cs, Alve Operating System/Alve OS/System/Time.cs, Alve Operating System/Alve OS/System/Translation/Keyboard.cs, Alve Operating System/Alve OS/System/Translation/Text/Color.cs, Alve Operating System/Alve OS/System/Translation/Text/Help.cs, Alve Operating System/Alve OS/System/Translation/Text/Text.cs, Alve Operating System/Alve OS/System/Users/Login.cs, Alve Operating System/Alve OS/System/Users/Setup.cs, Alve Operating System/Alve OS/System/Users/SetupInit.cs, Alve Operating System/Alve OS/System/Users/UserLevel.cs, Alve Operating System/Alve OS/System/Users/Users.cs
I think the title is enough to describe my pull request... :)
Able to merge.
=> Add Summary EVERYWHERE

Aura Operating System/Aura OS/Shell/cmdIntr/CommandManager.cs, Aura Operating System/Aura OS/Shell/cmdIntr/SystemInfomation/IPConfig.cs, Aura Operating System/Aura OS/System/Translation/Text/Text.cs
=> Impl Network ipconfig works !

Aura Operating System/Aura OS/Kernel.cs, Aura Operating System/Aura OS/System/Drawable/WelcomeMessage.cs, Aura Operating System/Aura OS/System/Users/Setup.cs
=> Setup improvements.

Aura Operating System/Aura OS/Apps/System/Batch.cs, Aura Operating System/Aura OS/Aura_OS.csproj, Aura Operating System/Aura OS/Aura_OSBoot.Cosmos, Aura Operating System/Aura OS/Shell/cmdIntr/CommandManager.cs, Aura Operating System/Aura OS/Shell/cmdIntr/FileSystem/Run.cs, Aura Operating System/Aura OS/System/Translation/Text/Text.cs
Ready to be merged.
All commands works (and new commands too).
=> Script Batch Interpreter

Aura Operating System/Aura OS/Aura_OSBoot.Cosmos, Aura Operating System/Aura OS/Kernel.cs, Aura Operating System/Aura OS/Shell/cmdIntr/CommandManager.cs, Aura Operating System/Aura OS/Shell/cmdIntr/Settings/Settings.cs, Aura Operating System/Aura OS/Shell/cmdIntr/c_Console/BackGroundColor.cs, Aura Operating System/Aura OS/Shell/cmdIntr/c_Console/TextColor.cs, Aura Operating System/Aura OS/System/Drawable/Logo.cs, Aura Operating System/Aura OS/System/Drawable/Menu.cs, Aura Operating System/Aura OS/System/Drawable/WelcomeMessage.cs, Aura Operating System/Aura OS/System/Translation/Text/Help.cs, Aura Operating System/Aura OS/System/Users/Setup.cs
Settings:
Progress bar:
Root:
Login:
=> Various changes.

Aura Operating System/Aura OS/Core/INTs.cs, Aura Operating System/Aura OS/System/Utils/Crash.cs
- Screen of death changed to a Windows Style :smiley:
- CPU exceptions now supported on the screen of death. (with Exception name, description and last known address.)
=> Screen of death Changes.

Aura Operating System/Aura OS/Apps/User/Editor.cs, Aura Operating System/Aura OS/Shell/cmdIntr/Settings/Settings.cs, Aura Operating System/Aura OS/System/Drawable/Logo.cs, Aura Operating System/Aura OS/System/Drawable/Menu.cs, Aura Operating System/Aura OS/System/Drawable/WelcomeMessage.cs, Aura Operating System/Aura OS/System/Translation/Keyboard.cs, Aura Operating System/Aura OS/System/Translation/Text/Help.cs, Aura Operating System/Aura OS/System/Translation/Text/Text.cs, Aura Operating System/Aura OS/System/Users/Login.cs, Aura Operating System/Aura OS/System/Users/Setup.cs, Aura Operating System/Aura OS/System/Utils/Time.cs
This adds support for the Dutch language to Aura.
=> Dutch language support

Aura Operating System/Aura OS/Aura_OS.csproj, Aura Operating System/Aura OS/Shell/cmdIntr/CommandManager.cs, Aura Operating System/Aura OS/Shell/cmdIntr/Util/xml/CmdXmlParser.cs, Aura Operating System/Aura OS/System/Parser/XML/NanoXMLParser.cs
=> First XML Implementation.

Aura Operating System/Aura OS/Kernel.cs, Aura Operating System/Aura OS/Shell/cmdIntr/CommandManager.cs, Aura Operating System/Aura OS/Shell/cmdIntr/Settings/Settings.cs, Aura Operating System/Aura OS/Shell/cmdIntr/SystemInfomation/SystemInfomation.cs, Aura Operating System/Aura OS/System/Computer/CPUInfo.cs, Aura Operating System/Aura OS/System/Computer/Info.cs, Aura Operating System/Aura OS/System/Translation/Text/List_Translation.cs, Aura Operating System/Aura OS/System/Translation/Text/Text.cs, Aura Operating System/Aura OS/System/Users/Setup.cs
Needs https://github.com/aura-systems/Cosmos/tree/impl-cpuinfo.
=> Systeminfo improvement + CPU Informations.

Aura Operating System/Aura OS/Aura_OS.csproj, Aura Operating System/Aura OS/Kernel.cs, Aura Operating System/Aura OS/Shell/cmdIntr/CommandManager.cs, Aura Operating System/Aura OS/System/Sound/PCSpeaker.cs, Aura Operating System/Aura OS/System/Translation/Text/Help.cs
No sound card just beeps with PCSpeaker ;)
To do:
=> First sound implementation.

Aura Operating System/Aura OS/System/Translation/Text/Text.cs
=> Added translation

Aura Operating System/Aura OS/System/Translation/Text/List_Translation.cs
=> Italian Translation added

Aura Operating System/Aura OS/System/Translation/Text/Text.cs
=> Updated Italian Traslation

Aura Operating System/Aura OS/System/Drawable/Menu.cs
Italia (name of the country) to italiano (name of the language)
=> Fixed a little typo

Aura Operating System/Aura OS/Shell/cmdIntr/Network/Ping.cs, Aura Operating System/Aura OS/System/Network.cs, Aura Operating System/Aura OS/System/Network/IPV4/Config.cs, Aura Operating System/Aura OS/System/Network/IPV4/OutgoingBuffer.cs
=> 🅱️⭕YC⭕TT  L🅰️N - Update

Aura Operating System/Aura OS/Shell/cmdIntr/CommandManager.cs, Aura Operating System/Aura OS/Shell/cmdIntr/Network/Ping.cs, Aura Operating System/Aura OS/System/Network/IPV4/UDP/DNS/DNSClient.cs, Aura Operating System/Aura OS/System/Network/IPV4/UDP/DNS/DNSPacket.cs, Aura Operating System/Aura OS/System/Network/IPV4/UDP/UDPPacket.cs
- Implementation of the DNS protocol
- DNS Command to get an IP from URL
=> DNS Protocol Implementation. 

Aura Operating System/Aura OS/Kernel.cs, Aura Operating System/Aura OS/System/Computer/Info.cs, Aura Operating System/Aura OS/System/Network.cs, Aura Operating System/Aura OS/System/Network/DHCP/Core.cs, Aura Operating System/Aura OS/System/Network/DHCP/DHCPPacket.cs, Aura Operating System/Aura OS/System/Network/IPV4/UDP/DNS/DNSClient.cs, Aura Operating System/Aura OS/System/Network/IPV4/UDP/DNS/DNSPacket.cs, Aura Operating System/Aura OS/System/Network/IPV4/UDP/UDPPacket.cs, Aura Operating System/Aura OS/System/Network/NetworkInterfaces.cs, Aura Operating System/Aura OS/System/Shell/cmdIntr/CommandManager.cs, Aura Operating System/Aura OS/System/Shell/cmdIntr/Settings/Settings.cs, Aura Operating System/Aura OS/System/Shell/cmdIntr/SystemInfomation/IPConfig.cs, Aura Operating System/Aura OS/System/Translation/Text/List_Translation.cs, Aura Operating System/Aura OS/System/Users/Login.cs, Aura Operating System/Aura OS/System/Users/Setup.cs, Aura Operating System/Aura OS/System/Utils/Settings.cs
Changelog :
1. Settings Class has been reworked.
2. Each interface has a now configuration file.
3. Use DNS though settings
4. Various optimization.
=> Core & Network Update for Aura 0.5

Aura Operating System/Aura OS/Apps/System/Batch.cs
add the ability to comment with the "|" char on script file
=> add the ability to comment with the "|" char

Aura Operating System/Aura_OS/System/Drawable/Menu.cs, Aura Operating System/Aura_OS/System/Drawable/WelcomeMessage.cs, Aura Operating System/Aura_OS/System/Translation/Keyboard.cs, Aura Operating System/Aura_OS/System/Translation/Text/List_Translation.cs, Aura Operating System/Aura_OS/System/Translation/Text/Text.cs
**Edited files:**
- Aura-Operating-System/Aura Operating System/Aura_OS/System/Drawable/WelcomeMessage.cs
- Aura-Operating-System/Aura Operating System/Aura_OS/System/Drawable/Menu.cs
- Aura-Operating-System/Aura Operating System/Aura_OS/System/Translation/Keyboard.cs
- Aura-Operating-System/Aura Operating System/Aura_OS/System/Translation/Text/List_Translation.cs
- Aura-Operating-System/Aura Operating System/Aura_OS/System/Translation/Text/Text.cs
**Added polish translation without special characters like "ć", "ą", "ę", "ż"**
It can be not full translation given very much files.
=> Create Polish Language

Aura Operating System/Aura_OS/Properties/VersionInfo.cs, Aura Operating System/Aura_OS/System/Shell/cmdIntr/CommandManager.cs, Aura Operating System/Aura_OS/System/Shell/cmdIntr/FileSystem/CD.cs, Aura Operating System/Aura_OS/System/Shell/cmdIntr/FileSystem/Cat.cs, Aura Operating System/Aura_OS/System/Shell/cmdIntr/FileSystem/ChangeVol.cs, Aura Operating System/Aura_OS/System/Shell/cmdIntr/FileSystem/Dir.cs, Aura Operating System/Aura_OS/System/Shell/cmdIntr/FileSystem/Hex.cs, Aura Operating System/Aura_OS/System/Shell/cmdIntr/FileSystem/Mkdir.cs, Aura Operating System/Aura_OS/System/Shell/cmdIntr/FileSystem/Mkfil.cs, Aura Operating System/Aura_OS/System/Shell/cmdIntr/FileSystem/Rmdir.cs, Aura Operating System/Aura_OS/System/Shell/cmdIntr/FileSystem/Rmfil.cs, Aura Operating System/Aura_OS/System/Shell/cmdIntr/FileSystem/Vol.cs, Aura Operating System/Aura_OS/System/Shell/cmdIntr/ICommand.cs, Aura Operating System/Aura_OS/System/Shell/cmdIntr/Network/Dns.cs, Aura Operating System/Aura_OS/System/Shell/cmdIntr/Network/IPConfig.cs, Aura Operating System/Aura_OS/System/Shell/cmdIntr/Network/Ping.cs, Aura Operating System/Aura_OS/System/Shell/cmdIntr/Network/Udp.cs, Aura Operating System/Aura_OS/System/Shell/cmdIntr/Power/Reboot.cs, Aura Operating System/Aura_OS/System/Shell/cmdIntr/Power/Shutdown.cs, Aura Operating System/Aura_OS/System/Shell/cmdIntr/SystemInfomation/SystemInfomation.cs, Aura Operating System/Aura_OS/System/Shell/cmdIntr/SystemInfomation/Time.cs, Aura Operating System/Aura_OS/System/Shell/cmdIntr/SystemInfomation/Version.cs, Aura Operating System/Aura_OS/System/Shell/cmdIntr/Tests/Crash.cs, Aura Operating System/Aura_OS/System/Shell/cmdIntr/Util/About.cs, Aura Operating System/Aura_OS/System/Shell/cmdIntr/Util/EnvVariables.cs, Aura Operating System/Aura_OS/System/Shell/cmdIntr/Util/Help.cs, Aura Operating System/Aura_OS/System/Shell/cmdIntr/c_Console/Clear.cs, Aura Operating System/Aura_OS/System/Shell/cmdIntr/c_Console/Echo.cs, Aura Operating System/Aura_OS/System/Shell/cmdIntr/c_Console/SetKeyboardMap.cs
=> Dynamic help command system

Aura Operating System/Aura_OS/System/Shell/cmdIntr/CommandManager.cs, Aura Operating System/Aura_OS/System/Shell/cmdIntr/CommandPCName.cs
"pcn" can change or display computer name.
=> Create ComputerName Manage

LICENSE.md, LICENSES/COSMOS/LICENSE.md, LICENSES/SDFS/LICENSE.md
Updated years to 2021, a new decade of Cosmosing and Aura :)
=> License patch

README_CN.md
I create Chinese translate for README.And I will follow up translaion.
=> Create Chinese translate for README

README_CN.md
I find some bugs in README translate.Just fix it.
=> Fix some bugs in translate
